[web3j]
url = "https://rpc.pulsechain.com"
chainId = 369
readerKey = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"


[maintainer]
contract = ""
# low-value keys to be used as executor. potential impact: loss of funds on the contract balance
executor = ""
bribe = 10
pollingInterval = "* * * * *"
