[web3j]
url = "https://rpc.pulsechain.com"
chainId = 369
readerKey = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"


[maintainer]
contract = "0x0cF34F5360CBE49D1b96e85132896F9355d62150"
# low-value keys to be used as executor. potential impact: loss of funds on the contract balance
#  dev account #1: 0xECeC79dBc71404c040d30046be9238f358a908a3
executor = ""
bribe = 10
pollingInterval = "31 18 * * 1"
