
web3j:
  node:
    url: https://rpc.pulsechain.com
    chainId: 369
    pollingInterval: 100

logging:
  level:
    root: error
    org:
      web3j:
        protocol: warn
    de:
      pribluda:
        eth:
          tanktruck: info


tanktruck:
  # contract address
  contract: '0xc3995B7D1Fd836e578B6F116b50B68f42B1975b8'
  # this shall be a low-value technical key for the address performing the contract execution.
  # supply executor primary key via the outside parameter, no do not write it here. Never!
  executorKey: "do not place real keys here. pass via parameter of whatever mechamism you use."
  # check every 120 seconds
  checkInterval: 120000
  # bribe above block base fee, %
  bribe: 5
