
web3j:
  node:
    url: https://rpc.pulsechain.com   # wss://rpc.pulsechain.com
    chainId: 369
    pollingInterval: 100

logging:
  level:
    root: error
    org:
      web3j:
        protocol: warn
    de:
      pribluda:
        eth:
          tanktruck: info


tanktruck:
  #  supply executor primary key via the outside parameter, no do not wrrite it here. Nexev
  executorKey: "do not place real keys here. pass via parameter of whatever you use."
  # check every 100 seconds
  checkInterval: 100000
  # list of addresses to refuel, comma separated
  addressList: "0x6661eac1901cf486d5A6D820f338c7C6668217A8,0x0470840ec5cdEB70B97f5c13C294e91463428B47"
  # refuel when it reaches thos threshold - 10K
  minAmount: 10000000000000000000000
  # refuel to this value 100K
  sendAmount: 100000000000000000000000